### ISSUE TITLE
4월 오프라인 모임을 가진다.

### ISSUE THREAD

**Issue by woowahanCU** [woowacourse/roadmap#16]
- [x] 날짜를 정한다.
- [x] 메뉴를 정한다.
- [x] 논의할 안건을 미리 생각해본다.

**Comment by woowahanCU** [comment]
회사에 출근하려면, 부문장 보고를 해야하므로 적당히 좋은 위치에서 저녁을 맛있게 먹는건 어떨까

**Comment by DaejunBae** [comment]
좋습니다! 저는 따로 보고는 필요 없어서 아무 때나 아무장소나 좋습니다!

**Comment by dpudpu** [comment]
좋습니다! 저는 따로 보고는 필요 없어서 아무 때나 아무장소나 좋습니다!

**Comment by woowahanCU** [comment]
저도 포비한테만 이야기하면 되는거라, 장소/시간 모두 괜찮습니다.
선호님(@vsh123 ) 스케줄에 맞추면 되겠군요.

**Comment by vsh123** [comment]
저희 팀은 매주 월요일은 원하면 출근을 할 수 있어서 월요일에 시간 괜찮을 것 같습니다!

다만 다음주 월요일까지 급하게 스프린트 작업할 건이 있어 시간은 27일쯤이 좋을 것 같은데 혹시 괜찮으신가요?

**Comment by woowahanCU** [comment]
@dpudpu @vsh123 

그럼 4월 27일 저녁으로 확정할까요?
