### ISSUE TITLE
로드맵 Contribution 문서를 작성한다.

### ISSUE THREAD

**Issue by woowahanCU** [woowacourse/roadmap#38]
테크코스 1, 2기 크루들 외에도 외부인들의 원활한 참여를 위해 Contribution 가이드 문서를 만드는 것은 어떨까요

**Comment by DaejunBae** [comment]
좋은 거 같아요 ! 
다음 모임까지 어느정도 룰 생각해서 이야기할까요?

**Comment by woowahanCU** [comment]
@DaejunBae 
이 이슈에서 계속 이야기해보시죠 ㅎㅎ
